input_arr = [
    {
        'img': 'picture1.jpg',
        'subject': 'Accountacy',
        'marks': '100',
        'name': 'PAYASVINI GUPTA',
        'sname': 'Holy Child School',
    },
    {
        'img': 'picture12.jpg',
        'subject': 'Economics',
        'marks': '100',
        'name': 'HIYA',
        'sname': 'Holy Child School',
    },
    {
        'img': 'picture20.jpg',
        'subject': 'Economics',
        'marks': '99',
        'name': 'MAANYA BAJAJ',
        'sname': 'Heritage School',
    },
    {
        'img': 'picture21.jpg',
        'subject': 'B. Studies',
        'marks': '99',
        'name': 'KAVYA GUPTA',
        'sname': 'Modern School',
    },
    {
        'img': 'picture14.jpg',
        'subject': 'B. Studies',
        'marks': '99',
        'name': 'CHEHAK AGGARWAL',
        'sname': '',
    },
    {
        'img': 'picture17.jpg',
        'subject': 'B. Studies',
        'marks': '99',
        'name': 'RISHABH KALRA',
        'sname': 'Springdales School',
    },
    {
        'img': 'picture3.jpg',
        'subject': 'Accountacy',
        'marks': '99',
        'name': 'KRITI MEHRA',
        'sname': 'Hansraj School',
    },
    {
        'img': 'picture3.jpg',
        'subject': 'Economics',
        'marks': '98',
        'name': 'KRITI MEHRA',
        'sname': 'Hansraj School',
    },
    {
        'img': 'picture4.jpg',
        'subject': 'Accountacy',
        'marks': '98',
        'name': 'AKSHAT BANSAL',
        'sname': 'Doon Public School',
    },
    {
        'img': 'picture22.jpg',
        'subject': 'Accountacy',
        'marks': '98',
        'name': 'JASNOOR KAUR',
        'sname': 'Apeejay School',
    },
    {
        'img': 'picture23.jpg',
        'subject': 'B. Studies',
        'marks': '98',
        'name': 'JASRAJ MARWAH',
        'sname': 'Sardar Patel Vidyalaya',
    },
    {
        'img': 'picture5.jpg',
        'subject': 'Accountacy',
        'marks': '97',
        'name': 'ANJALI GOEL',
        'sname': 'Doon Public School',
    },
    {
        'img': 'picture6.jpg',
        'subject': 'Accountacy',
        'marks': '97',
        'name': 'STUTI SETHI',
        'sname': 'Modern School',
    },
    {
        'img': 'picture13.jpg',
        'subject': 'B. Studies',
        'marks': '97',
        'name': 'RISHABH SHARMA',
        'sname': 'Hansraj Model School',
    },
    {
        'img': 'picture15.jpg',
        'subject': 'B. Studies',
        'marks': '97',
        'name': 'SANCHI SETHI',
        'sname': 'Springdales School',
    },
    {
        'img': 'picture16.jpg',
        'subject': 'Accountacy',
        'marks': '97',
        'name': 'SAHIL GUPTA',
        'sname': 'Hansraj School',
    },
    {
        'img': 'picture19.jpg',
        'subject': 'Accountacy',
        'marks': '97',
        'name': 'NITISH GUPTA',
        'sname': 'Hansraj Model School',
    },
    {
        'img': 'picture24.jpg',
        'subject': 'B. Studies',
        'marks': '97',
        'name': 'GESHNA GULATI',
        'sname': '',
    },
    {
        'img': 'picture25.jpg',
        'subject': 'B. Studies',
        'marks': '97',
        'name': 'KRITI SETHI',
        'sname': 'Maxfort School',
    },
    {
        'img': 'picture2.jpg',
        'subject': 'Accountacy',
        'marks': '96',
        'name': 'MAANYA SHARMA',
        'sname': 'G. D. Goenka Public School',
    },
    {
        'img': 'picture7.jpg',
        'subject': 'Accountacy',
        'marks': '96',
        'name': 'RIDHI KALRA',
        'sname': 'Delhi Publi School( M. Road)',
    },
    {
        'img': 'picture8.jpg',
        'subject': 'Accountacy',
        'marks': '96',
        'name': 'MEHAK GULATI',
        'sname': 'Heritage School',
    },
    {
        'img': 'picture24.jpg',
        'subject': 'Economics',
        'marks': '96',
        'name': 'GESHNA GULATI',
        'sname': '',
    },
    {
        'img': 'picture26.jpg',
        'subject': 'Accountacy',
        'marks': '96',
        'name': 'VANSHIKA SHARMA',
        'sname': 'DAV School',
    },
    {
        'img': 'picture27.jpg',
        'subject': 'Accountacy',
        'marks': '96',
        'name': 'LAKSHAY JAIN',
        'sname': 'Air Force School',
    },
    {
        'img': 'picture27.jpg',
        'subject': 'B. Studies',
        'marks': '96',
        'name': 'LAKSHAY JAIN',
        'sname': 'Air Force School',
    },
    {
        'img': 'picture25.jpg',
        'subject': 'Accountacy',
        'marks': '96',
        'name': 'KRITI SETHI',
        'sname': 'Maxfort School',
    },
    {
        'img': 'picture2.jpg',
        'subject': 'Economics',
        'marks': '95',
        'name': 'MAANYA SHARMA',
        'sname': 'G. D. Goenka Public School',
    },
    {
        'img': 'picture4.jpg',
        'subject': 'Economics',
        'marks': '95',
        'name': 'AKSHAT BANSAL',
        'sname': 'Doon Public School',
    },
    {
        'img': 'picture7.jpg',
        'subject': 'B. Studies',
        'marks': '95',
        'name': 'RIDHI KALRA',
        'sname': 'Delhi Public School(M. Road)',
    },
    {
        'img': 'picture9.jpg',
        'subject': 'Accountacy',
        'marks': '95',
        'name': 'YATIN AGGRAWAL',
        'sname': 'St. Martin School',
    },
    {
        'img': 'picture9.jpg',
        'subject': 'Economics',
        'marks': '95',
        'name': 'YATIN AGGRAWAL',
        'sname': 'St. Martin School',
    },
    {
        'img': 'picture10.jpg',
        'subject': 'Accountacy',
        'marks': '95',
        'name': 'SHRISHTI GUPTA',
        'sname': 'St. Martin School',
    },
    {
        'img': 'picture10.jpg',
        'subject': 'Economics',
        'marks': '95',
        'name': 'SHRISHTI GUPTA',
        'sname': 'St. Martin School',
    },
    {
        'img': 'picture11.jpg',
        'subject': 'Accountacy',
        'marks': '95',
        'name': 'SNIGDHA BUDDHIRAJA',
        'sname': 'Delhi Public School(RK Puram)',
    },
    {
        'img': 'picture11.jpg',
        'subject': 'Economics',
        'marks': '95',
        'name': 'SNIGDHA BUDDHIRAJA',
        'sname': 'Delhi Public School(RK Puram)',
    },
    {
        'img': 'picture11.jpg',
        'subject': 'B. Studies',
        'marks': '95',
        'name': 'SNIGDHA BUDDHIRAJA',
        'sname': 'Delhi Public School(RK Puram)',
    },
    {
        'img': 'picture13.jpg',
        'subject': 'Accountacy',
        'marks': '95',
        'name': 'RISHABH SHARMA',
        'sname': 'Hansraj School',
    },
    {
        'img': 'picture13.jpg',
        'subject': 'Economics',
        'marks': '95',
        'name': 'RISHABH SHARMA',
        'sname': 'Hansraj School',
    },
    {
        'img': 'picture14.jpg',
        'subject': 'Accountacy',
        'marks': '95',
        'name': 'CHEHAK AGGARWAL',
        'sname': '',
    },
    {
        'img': 'picture16.jpg',
        'subject': 'Accountacy',
        'marks': '95',
        'name': 'SAHIL GUPTA',
        'sname': 'Hansraj School',
    },
    {
        'img': 'picture17.jpg',
        'subject': 'Accountacy',
        'marks': '95',
        'name': 'RISHABH KALRA',
        'sname': 'Hansraj School',
    },
    {
        'img': 'picture18.jpg',
        'subject': 'Accountacy',
        'marks': '95',
        'name': 'MANCHIT KAUR',
        'sname': 'New Era School',
    },
    {
        'img': 'picture18.jpg',
        'subject': 'Economics',
        'marks': '95',
        'name': 'MANCHIT KAUR',
        'sname': 'New Era School',
    },
    {
        'img': 'picture18.jpg',
        'subject': 'B. Studies',
        'marks': '95',
        'name': 'MANCHIT KAUR',
        'sname': 'New Era School',
    },
    {
        'img': 'picture28.jpg',
        'subject': 'Accountacy',
        'marks': '95',
        'name': 'RISHIKA GIRI',
        'sname': 'Ryan International School',
    },
    {
        'img': 'picture28.jpg',
        'subject': 'Economics',
        'marks': '95',
        'name': 'RISHIKA GIRI',
        'sname': 'Ryan International School',
    },
    {
        'img': 'picture28.jpg',
        'subject': 'B. Studies',
        'marks': '95',
        'name': 'RISHIKA GIRI',
        'sname': 'Ryan International School',
    },
    {
        'img': 'picture27.jpg',
        'subject': 'Economics',
        'marks': '95',
        'name': 'LAKSHAY JAIN',
        'sname': 'Air Force School',
    },
    {
        'img': 'picture21.jpg',
        'subject': 'Accountacy',
        'marks': '95',
        'name': 'KAVYA GUPTA',
        'sname': 'Modern School',
    },
    {
        'img': 'picture25.jpg',
        'subject': 'Economics',
        'marks': '95',
        'name': 'KRITI SETHI',
        'sname': 'Maxfort School',
    }





    , {
        'img': 'she.jpg',
        'subject': 'Economics',
        'marks': '99',
        'name': 'MRINALINI ARORA',
        'sname': 'Springdales School',
    },
    {
        'img': 'she.jpg',
        'subject': 'B. Studies',
        'marks': '98',
        'name': 'JAHNAVI JINDAL',
        'sname': 'Vishal Bharti School',
    },
    {
        'img': 'she.jpg',
        'subject': 'B. Studies',
        'marks': '98',
        'name': 'MRINALINI ARORA',
        'sname': 'Springdales School',
    },
    {
        'img': 'he.jpg',
        'subject': 'Accountacy',
        'marks': '98',
        'name': 'VAIBHAV SETH',
        'sname': 'Mount St. Mary School',
    },
    {
        'img': 'she.jpg',
        'subject': 'Accountacy',
        'marks': '98',
        'name': 'VANSHIKA',
        'sname': 'N. C. Jindal School',
    },
    {
        'img': 'she.jpg',
        'subject': 'Economics',
        'marks': '97',
        'name': 'JAHNAVI JINDAL',
        'sname': 'Vishal Bharti School',
    },
    {
        'img': 'he.jpg',
        'subject': 'Accountancy',
        'marks': '97',
        'name': 'KRISH SETH',
        'sname': 'Indraprastha World School',
    },
    {
        'img': 'she.jpg',
        'subject': 'Accountancy',
        'marks': '96',
        'name': 'ANSHIKA SHARMA',
        'sname': 'Apeejay School',
    },
    {
        'img': 'she.jpg',
        'subject': 'Accountancy',
        'marks': '96',
        'name': 'JAHNAVI JINDAL',
        'sname': 'Vishal Bharti School',
    },
    {
        'img': 'she.jpg',
        'subject': 'Accountancy',
        'marks': '96',
        'name': 'MRINALINI ARORA',
        'sname': 'Springdales School',
    },
    {
        'img': 'he.jpg',
        'subject': 'B. Studies',
        'marks': '95',
        'name': 'KAARTIK CHUGH',
        'sname': 'St. marks School',
    },
    {
        'img': 'she.jpg',
        'subject': 'Accountancy',
        'marks': '95',
        'name': 'KASHISH OBEROI',
        'sname': 'Holy Child School',
    },
    {
        'img': 'she.jpg',
        'subject': 'B. Studies',
        'marks': '95',
        'name': 'NANDINI KAPOOR',
        'sname': 'Bhatnagar International School',
    },
    {
        'img': 'she.jpg',
        'subject': 'Economics',
        'marks': '95',
        'name': 'NANDINI KAPOOR',
        'sname': 'Bhatnagar International School',
    },
    {
        'img': 'she.jpg',
        'subject': 'Accountancy',
        'marks': '95',
        'name': 'RIDHI GUPTA',
        'sname': 'Indraprastha World School',
    },
    {
        'img': 'she.jpg',
        'subject': 'Accountancy',
        'marks': '95',
        'name': 'SHREYA GARG',
        'sname': 'Apeejay School',
    },
    {
        'img': 'she.jpg',
        'subject': 'Accountancy',
        'marks': '95',
        'name': 'TANISHA',
        'sname': 'Mother Divine School',
    },

]

output_arr = []
students = {}

for item in input_arr:
    student_name = item['name']
    if student_name in students:
        # Student already exists in the dictionary
        students[student_name]['subject'].append(item['subject'])
        students[student_name]['marks'].append(item['marks'])
    else:
        # New student
        students[student_name] = {
            'img': item['img'],
            'subject': [item['subject']],
            'marks': [item['marks']],
            'name': item['name'],
            'sname': item['sname']
        }

# Convert the dictionary back to an array
for student in students.values():
    output_arr.append(student)

print(output_arr)
