import Head from "next/head"
import Gallery from '@/components/Gallery'
import Footer from '@/components/Footer'
import Navbar from "@/components/Navbar"


export default function Home() {
    return (
        <>
            <Head>
                <title>Forward Education | Gallery</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <Gallery />
            <Footer />
        </>
    )
}