import Head from 'next/head'
import Image from 'next/image'
import next from "../public/next.svg"
import Navbar from '@/components/Navbar'
import Hero from '@/components/Hero'
import About from '@/components/About'
import Whyus from '@/components/Whyus'
import Subject from '@/components/Subject'
import Teacher from '@/components/Teacher'
import Reviews from '@/components/Reviews'
import Footer from '@/components/Footer'
import Stats from '@/components/Stats'

import { sectionData } from '@/utility/data'
import React, { useState, useEffect } from 'react'
// import Popup from '../components/Popup'
// import LowerHalf from '@/components/LowerHalf'



export default function Home() {
  const renderStatData = sectionData.map((data, index) => (
    <Stats
      key={index}
      number={data.number}
      title={data.title}
      suffix={data.suffix}
    />
  ));



  return (
    <>
      <Head>
        <title>Forward Education</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />


      </Head>
      <Navbar />
      <div className='flex flex-col space-y-14'>
        <Hero />
        <About />
        <div className='grid md:grid-cols-4  grid-cols-2 gri-cols-1 px-5 md:px-0 w-full gap-8 max-w-5xl mx-auto'>
          {renderStatData}
        </div>
        <Whyus />
        <Subject />
        <Teacher />
      </div>


      {/* <Reviews /> */}
      <Footer />




    </>
  )
}







